version: '3'

services:
  gestionuniversitaire:
    image: gestionuniversitaire
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://gestionuniversitaire-mysql:3306/gestionuniversitaire?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://gestionuniversitaire-mysql:3306/gestionuniversitaire?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    ports:
      - '8080:8080'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40

  gestionuniversitaire-mysql:
    image: mysql:8.2.0
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gestionuniversitaire
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test:
        - CMD
        - mysql
        - '-e'
        - SHOW DATABASES;
      interval: 5s
      timeout: 5s
      retries: 10

  sonarqube:
    container_name: sonarqube
    image: sonarqube:10.2.1-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9000'

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000']
      interval: 30s
      timeout: 10s
      retries: 5
